server:
  port: 9003
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka
   
kafka:
  bootstrapAddress: localhost:9092
  topic:
    helloworld: helloworld.t
    json: json.t
    partitioned: partition.t